version: "3"
services:
  cuda:
    image: cuda-image
    container_name: cuda
    build:
      context: .
      dockerfile: dockerfile.Docker
    network_mode: host
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu,compute,utility,graphics,display]
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/app/cuda
    # -RenderOffScreen
    command: tail -F anything
    restart: always
